api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    title: 'Myddleware 3 API'
    description: 'The Myddleware API allows you to run Myddleware commands related to your rules.'
    version: '2.0.0'
    openapi:
        contact:
            name: Stéphane Faure
            email: contact@myddleware.com
