framework:
    messenger:
        reset_on_message: true
        transports:
            # async:
            #     dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
            failed: 'doctrine://default?queue_name=failed'
            sync: 'sync://'
            
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        routing:
            # Route your messages to the transports
            # 'App\Message\YourMessage': async
