exclude_patterns:
  - "**/*.*"
  - "!src/Myddleware/RegleBundle/Solutions/vtigercrm.php"

engines:
  duplication:
    enabled: false
  fixme:
    enabled: true
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php"
      standard: "PSR1,PSR2"
      ignore_warnings: false
  phpmd:
    enabled: true
    config:
      file_extensions: "php"
      rulesets: "unusedcode,codesize,naming"
