# This file describes an application. You can have multiple applications
# in the same project.

# The name of this app. Must be unique within a project.
name: myddleware

# The type of the application to build.
type: php:7.1
build:
    flavor: composer

# The extensions you want to enable.
runtime:
    extensions:
        - ssh2
        - pdo_dblib

# The relationships of the application with services or other applications.
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
# side is in the form `<service name>:<endpoint name>`.
relationships:
    database: "mysqldb:mysql"

# The configuration of app when it is exposed to the web.
web:
    locations:
        "/":
            # The public directory of the app, relative to its root.
            root: "web"
            # The front-controller script to send non-static requests to.
            passthru: "/app.php"

# The size of the persistent disk of the application (in MB).
disk: 2048

# The mounts that will be performed when the package is deployed.
mounts:
    "/var/cache": "shared:files/cache"
    "/var/logs": "shared:files/logs"
    "/app/config/public": "shared:files/config/public"
    "/var/sessions": "shared:files/sessions"
    "/src": "shared:files/src"
    "/web": "shared:files/web"
    "/vendor": "shared:files/vendor"

# The hooks that will be performed when the package is deployed.
hooks:
    build: |
        php bin/console --env=prod assets:install --no-debug
    deploy: |
        php bin/console --env=prod cache:clear
        php bin/console --env=prod assetic:dump
        php bin/console --env=prod assets:install web
        php bin/console d:s:u --force
        php bin/console d:f:l --append
        php bin/console fos:user:create admin admin@example.com admin
        php bin/console fos:user:promote admin ROLE_ADMIN

crons:
    jobScheduler:
        spec: '*/5 * * * *'
        cmd: 'php bin/console myddleware:jobScheduler --env=background'
