preset: recommended

enabled:
  - phpdoc_add_missing_param_annotation
  #- void_return  # PHP 7 only

disabled:
  - no_empty_phpdoc

finder:
  name:
    - vtigercrm.php
  path:
    - src/Myddleware/RegleBundle/Solutions
