preset: recommended

enabled:
  #- void_return
  - phpdoc_add_missing_param_annotation

disabled:
  - no_empty_phpdoc

finder:  
  exclude:    
    - ".platform"
    - "app"
    - "bin"
    - "devops"
    - "src"
    - "tests"
    - "var"
    - "web"
  path:
    - "src/Myddleware/RegleBundle/Solutions/vtigercrm.php"    
    
