version: '2'

services:

  myddleware:
    environment:
      - VT_CLIENT_LOG_FILE=/var/www/html/var/logs/vtigercrm.log
      - MYSQL_DATABASE=myddleware
      - MYSQL_ROOT_PASSWORD=secret
    links:
      - phpmyadmin

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - ${phpmyadmin_port}:80
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=secret
    links:
      - mysql

  vtiger1:
    image: javanile/vtiger:7.1.0
    ports:
      - ${vtiger1_port}:80
    environment:
      - MYSQL_HOST=mysql1
      - MYSQL_DATABASE=vtiger
      - MYSQL_ROOT_PASSWORD=secret
    links:
      - mysql1

  mysql1:
    image: mysql:5.7.28
    command: --sql-mode=
    environment:
      - MYSQL_DATABASE=vtiger
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - mysql1:/var/lib/mysql:rw

  vtiger2:
    image: javanile/vtiger:7.1.0
    ports:
      - ${vtiger2_port}:80
    environment:
      - MYSQL_HOST=mysql2
      - MYSQL_DATABASE=vtiger
      - MYSQL_ROOT_PASSWORD=secret
    links:
      - mysql2

  mysql2:
    image: mysql:5.7.28
    command: --sql-mode=
    environment:
      - MYSQL_DATABASE=vtiger
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - mysql2:/var/lib/mysql:rw

  mssql:
    image: javanile/mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Secret.1234!
    volumes:
      - mssql:/var/opt/mssql/data

  adminer:
    image: adminer
    ports:
      - ${adminer_port}:8080

volumes:
  mysql1:
  mysql2:
  mssql:
