version: '3'

services:

  myddleware:
    build: .
    environment:
      - MYSQL_DATABASE=myddleware
      - MYSQL_ROOT_PASSWORD=secret
      - VT_CLIENT_LOG_FILE=/var/www/html/var/logs/vtigercrm.log
    links:
      - phpmyadmin

  phpmyadmin:
    environment:
      - PMA_USER=root
      - PMA_PASSWORD=secret

  vtiger1:
    image: javanile/vtiger:7.1.0
    ports:
      - ${vtiger1_port:-30081}:80
    environment:
      - MYSQL_HOST=mysql1
      - MYSQL_DATABASE=vtiger
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - .:/app
      - ./dev/opencrmitalia_modules:/app/opencrmitalia_modules
    links:
      - mysql1

  mysql1:
    image: mysql:5.7.28
    command: --sql-mode=
    environment:
      - MYSQL_DATABASE=vtiger
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - mysql1:/var/lib/mysql:rw

  phpmyadmin1:
    image: phpmyadmin/phpmyadmin
    ports:
      - ${phpmyadmin1_port:-30091}:80
    environment:
      - PMA_HOST=mysql1
      - PMA_USER=root
      - PMA_PASSWORD=secret
    links:
      - mysql1

  vtiger2:
    image: javanile/vtiger:7.1.0
    ports:
      - ${vtiger2_port:-30082}:80
    environment:
      - MYSQL_HOST=mysql2
      - MYSQL_DATABASE=vtiger
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - .:/app
      - ./dev/opencrmitalia_modules:/app/opencrmitalia_modules
    links:
      - mysql2

  mysql2:
    image: mysql:5.7.28
    command: --sql-mode=
    environment:
      - MYSQL_DATABASE=vtiger
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - mysql2:/var/lib/mysql:rw

  phpmyadmin2:
    image: phpmyadmin/phpmyadmin
    ports:
      - ${phpmyadmin2_port:-30092}:80
    environment:
      - PMA_HOST=mysql2
      - PMA_USER=root
      - PMA_PASSWORD=secret
    links:
      - mysql2

  mssql:
    image: javanile/mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Secret.1234!
    volumes:
      - ./dev/fixtures:/fixtures
      - mssql:/var/opt/mssql/data

  adminer:
    image: adminer
    ports:
      - ${adminer_port:-30099}:8080

volumes:
  mysql1:
  mysql2:
  mssql:
