api_synchro:
    path:  /v1_0/synchro
    defaults: { _controller: MyddlewareApiBundle:Default:synchro }
    requirements:
        methods:  POST
        
api_read_record:
    path:  /v1_0/read_record
    defaults: { _controller: MyddlewareApiBundle:Default:readRecord }
    requirements:
        methods:  POST
        
api_delete_record:
    path:  /v1_0/delete_record
    defaults: { _controller: MyddlewareApiBundle:Default:deleteRecord }
    requirements:
        methods:  POST
        
api_mass_action:
    path:  /v1_0/mass_action
    defaults: { _controller: MyddlewareApiBundle:Default:massAction }
    requirements:
        methods:  POST

api_rerun_error:
    path:  /v1_0/rerun_error
    defaults: { _controller: MyddlewareApiBundle:Default:rerunError }
    requirements:
        methods:  POST

api_statistics:
    path:  /v1_0/statistics
    defaults: { _controller: MyddlewareApiBundle:Default:statistics }
    requirements:
        methods:  POST

