api_synchro:
    path:  /v1_0/synchro
    defaults: { _controller: MyddlewareApiBundle:Default:synchro }
    requirements:
        methods:  POST
        
api_read_record:
    path:  /v1_0/read_record
    defaults: { _controller: MyddlewareApiBundle:Default:readRecord }
    requirements:
        methods:  POST

api_mass_action:
    path:  /v1_0/mass_action
    defaults: { _controller: MyddlewareApiBundle:Default:massAction }
    requirements:
        methods:  POST

