<?php

/*********************************************************************************
 * This file is part of Myddleware.
 *
 * @package Myddleware
 * @copyright Copyright (C) 2013 - 2015  Stéphane Faure - CRMconsult EURL
 * @copyright Copyright (C) 2015 - 2026  Stéphane Faure - Myddleware ltd - contact@myddleware.com
 * @link http://www.myddleware.com
 *
 * Myddleware is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *********************************************************************************/

$moduleFields = [
    'thirdparties' => [
        'id' => ['label' => 'ID', 'type' => 'int', 'required' => 0],
        'rowid' => ['label' => 'Row ID', 'type' => 'int', 'required' => 0],
        'ref' => ['label' => 'Reference', 'type' => 'string', 'required' => 0],
        'nom' => ['label' => 'Name', 'type' => 'string', 'required' => 0],
        'name_alias' => ['label' => 'Alias', 'type' => 'string', 'required' => 0],
        'client' => ['label' => 'Customer', 'type' => 'bool', 'required' => 0],
        'fournisseur' => ['label' => 'Supplier', 'type' => 'bool', 'required' => 0],
        'email' => ['label' => 'Email', 'type' => 'string', 'required' => 0],
        'phone' => ['label' => 'Phone', 'type' => 'string', 'required' => 0],
        'town' => ['label' => 'Town', 'type' => 'string', 'required' => 0],
        'zip' => ['label' => 'Zip', 'type' => 'string', 'required' => 0],
        'country_code' => ['label' => 'Country code', 'type' => 'string', 'required' => 0],
        'status' => ['label' => 'Status', 'type' => 'int', 'required' => 0],
        'tms' => ['label' => 'Modified date', 'type' => 'datetime', 'required' => 0],
    ],
    'contacts' => [
        'id' => ['label' => 'ID', 'type' => 'int', 'required' => 0],
        'rowid' => ['label' => 'Row ID', 'type' => 'int', 'required' => 0],
        'ref' => ['label' => 'Reference', 'type' => 'string', 'required' => 0],
        'lastname' => ['label' => 'Last name', 'type' => 'string', 'required' => 0],
        'firstname' => ['label' => 'First name', 'type' => 'string', 'required' => 0],
        'email' => ['label' => 'Email', 'type' => 'string', 'required' => 0],
        'phone_mobile' => ['label' => 'Mobile phone', 'type' => 'string', 'required' => 0],
        'phone_pro' => ['label' => 'Business phone', 'type' => 'string', 'required' => 0],
        'socid' => ['label' => 'Third party ID', 'type' => 'int', 'required' => 0],
        'poste' => ['label' => 'Job title', 'type' => 'string', 'required' => 0],
        'statut' => ['label' => 'Status', 'type' => 'int', 'required' => 0],
        'tms' => ['label' => 'Modified date', 'type' => 'datetime', 'required' => 0],
    ],
    'products' => [
        'id' => ['label' => 'ID', 'type' => 'int', 'required' => 0],
        'rowid' => ['label' => 'Row ID', 'type' => 'int', 'required' => 0],
        'ref' => ['label' => 'Reference', 'type' => 'string', 'required' => 0],
        'label' => ['label' => 'Label', 'type' => 'string', 'required' => 0],
        'description' => ['label' => 'Description', 'type' => 'string', 'required' => 0],
        'price' => ['label' => 'Price', 'type' => 'float', 'required' => 0],
        'price_ttc' => ['label' => 'Price incl. tax', 'type' => 'float', 'required' => 0],
        'status' => ['label' => 'Status', 'type' => 'int', 'required' => 0],
        'tms' => ['label' => 'Modified date', 'type' => 'datetime', 'required' => 0],
    ],
    'invoices' => [
        'id' => ['label' => 'ID', 'type' => 'int', 'required' => 0],
        'rowid' => ['label' => 'Row ID', 'type' => 'int', 'required' => 0],
        'ref' => ['label' => 'Reference', 'type' => 'string', 'required' => 0],
        'socid' => ['label' => 'Third party ID', 'type' => 'int', 'required' => 0],
        'date' => ['label' => 'Invoice date', 'type' => 'date', 'required' => 0],
        'total_ht' => ['label' => 'Total excl. tax', 'type' => 'float', 'required' => 0],
        'total_tva' => ['label' => 'Tax total', 'type' => 'float', 'required' => 0],
        'total_ttc' => ['label' => 'Total incl. tax', 'type' => 'float', 'required' => 0],
        'statut' => ['label' => 'Status', 'type' => 'int', 'required' => 0],
        'tms' => ['label' => 'Modified date', 'type' => 'datetime', 'required' => 0],
    ],
    'orders' => [
        'id' => ['label' => 'ID', 'type' => 'int', 'required' => 0],
        'rowid' => ['label' => 'Row ID', 'type' => 'int', 'required' => 0],
        'ref' => ['label' => 'Reference', 'type' => 'string', 'required' => 0],
        'socid' => ['label' => 'Third party ID', 'type' => 'int', 'required' => 0],
        'date_commande' => ['label' => 'Order date', 'type' => 'date', 'required' => 0],
        'total_ht' => ['label' => 'Total excl. tax', 'type' => 'float', 'required' => 0],
        'total_tva' => ['label' => 'Tax total', 'type' => 'float', 'required' => 0],
        'total_ttc' => ['label' => 'Total incl. tax', 'type' => 'float', 'required' => 0],
        'statut' => ['label' => 'Status', 'type' => 'int', 'required' => 0],
        'tms' => ['label' => 'Modified date', 'type' => 'datetime', 'required' => 0],
    ],
    'proposals' => [
        'id' => ['label' => 'ID', 'type' => 'int', 'required' => 0],
        'rowid' => ['label' => 'Row ID', 'type' => 'int', 'required' => 0],
        'ref' => ['label' => 'Reference', 'type' => 'string', 'required' => 0],
        'socid' => ['label' => 'Third party ID', 'type' => 'int', 'required' => 0],
        'datep' => ['label' => 'Proposal date', 'type' => 'date', 'required' => 0],
        'fin_validite' => ['label' => 'Validity end', 'type' => 'date', 'required' => 0],
        'total_ht' => ['label' => 'Total excl. tax', 'type' => 'float', 'required' => 0],
        'total_ttc' => ['label' => 'Total incl. tax', 'type' => 'float', 'required' => 0],
        'statut' => ['label' => 'Status', 'type' => 'int', 'required' => 0],
        'tms' => ['label' => 'Modified date', 'type' => 'datetime', 'required' => 0],
    ],
    'tickets' => [
        'id' => ['label' => 'ID', 'type' => 'int', 'required' => 0],
        'rowid' => ['label' => 'Row ID', 'type' => 'int', 'required' => 0],
        'ref' => ['label' => 'Reference', 'type' => 'string', 'required' => 0],
        'subject' => ['label' => 'Subject', 'type' => 'string', 'required' => 0],
        'message' => ['label' => 'Message', 'type' => 'string', 'required' => 0],
        'fk_soc' => ['label' => 'Third party ID', 'type' => 'int', 'required' => 0],
        'fk_user_create' => ['label' => 'Created by', 'type' => 'int', 'required' => 0],
        'status' => ['label' => 'Status', 'type' => 'int', 'required' => 0],
        'tms' => ['label' => 'Modified date', 'type' => 'datetime', 'required' => 0],
    ],
    'projects' => [
        'id' => ['label' => 'ID', 'type' => 'int', 'required' => 0],
        'rowid' => ['label' => 'Row ID', 'type' => 'int', 'required' => 0],
        'ref' => ['label' => 'Reference', 'type' => 'string', 'required' => 0],
        'title' => ['label' => 'Title', 'type' => 'string', 'required' => 0],
        'description' => ['label' => 'Description', 'type' => 'string', 'required' => 0],
        'public' => ['label' => 'Public', 'type' => 'bool', 'required' => 0],
        'usage_opportunities' => ['label' => 'Usage opportunities', 'type' => 'bool', 'required' => 0],
        'date_start' => ['label' => 'Start date', 'type' => 'date', 'required' => 0],
        'date_end' => ['label' => 'End date', 'type' => 'date', 'required' => 0],
        'tms' => ['label' => 'Modified date', 'type' => 'datetime', 'required' => 0],
    ],
    'tasks' => [
        'id' => ['label' => 'ID', 'type' => 'int', 'required' => 0],
        'rowid' => ['label' => 'Row ID', 'type' => 'int', 'required' => 0],
        'ref' => ['label' => 'Reference', 'type' => 'string', 'required' => 0],
        'label' => ['label' => 'Label', 'type' => 'string', 'required' => 0],
        'description' => ['label' => 'Description', 'type' => 'string', 'required' => 0],
        'fk_project' => ['label' => 'Project ID', 'type' => 'int', 'required' => 0],
        'dateo' => ['label' => 'Start date', 'type' => 'date', 'required' => 0],
        'datee' => ['label' => 'End date', 'type' => 'date', 'required' => 0],
        'progress' => ['label' => 'Progress', 'type' => 'int', 'required' => 0],
        'tms' => ['label' => 'Modified date', 'type' => 'datetime', 'required' => 0],
    ],
    'supplierorders' => [
        'id' => ['label' => 'ID', 'type' => 'int', 'required' => 0],
        'rowid' => ['label' => 'Row ID', 'type' => 'int', 'required' => 0],
        'ref' => ['label' => 'Reference', 'type' => 'string', 'required' => 0],
        'socid' => ['label' => 'Supplier ID', 'type' => 'int', 'required' => 0],
        'date_commande' => ['label' => 'Order date', 'type' => 'date', 'required' => 0],
        'total_ht' => ['label' => 'Total excl. tax', 'type' => 'float', 'required' => 0],
        'total_ttc' => ['label' => 'Total incl. tax', 'type' => 'float', 'required' => 0],
        'statut' => ['label' => 'Status', 'type' => 'int', 'required' => 0],
        'tms' => ['label' => 'Modified date', 'type' => 'datetime', 'required' => 0],
    ],
    'supplierinvoices' => [
        'id' => ['label' => 'ID', 'type' => 'int', 'required' => 0],
        'rowid' => ['label' => 'Row ID', 'type' => 'int', 'required' => 0],
        'ref' => ['label' => 'Reference', 'type' => 'string', 'required' => 0],
        'socid' => ['label' => 'Supplier ID', 'type' => 'int', 'required' => 0],
        'date' => ['label' => 'Invoice date', 'type' => 'date', 'required' => 0],
        'total_ht' => ['label' => 'Total excl. tax', 'type' => 'float', 'required' => 0],
        'total_tva' => ['label' => 'Tax total', 'type' => 'float', 'required' => 0],
        'total_ttc' => ['label' => 'Total incl. tax', 'type' => 'float', 'required' => 0],
        'statut' => ['label' => 'Status', 'type' => 'int', 'required' => 0],
        'tms' => ['label' => 'Modified date', 'type' => 'datetime', 'required' => 0],
    ],
];
