imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: error
        firephp:
            type:  firephp
            level: error
        chromephp:
            type:  chromephp
            level: error

assetic:
    use_controller: true
    
services:
    twig.extension.debug:
        class: Twig_Extension_Debug
        tags:
             - { name: 'twig.extension' }

#swiftmailer:
#    delivery_address: me@example.com
