parameters:
    mailer_transport: null
    mailer_host: null
    mailer_port: null
    mailer_auth_mode: null
    mailer_user: null
    mailer_password: null
    mailer_email: null
    mailer_name: null
