<?php

// Aiko
$moduleFields['appdKFUpk2X2Ok8Dc'] = array (
    'CONTACTS' => array(
        'ID___COMET'=> array( 'label' => 'ID Comet', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 1, 'relate' => false),
        'STATUS' => array( 'label' => 'Status', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 1, 'relate' => false),
        'NOM' => array( 'label' => 'Nom', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
        'PRENOM' => array( 'label' => 'Prénom', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
        'EMAIL'=> array( 'label' => 'Email', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
        'MOBILE'=> array( 'label' => 'Mobile', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
        'REFERENT DE'=> array( 'label' => 'Référent de', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
        'DATE___DE___NAISSANCE'=> array( 'label' => 'Date de naissance', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
        'Civilité'=> array( 'label' => 'Civilité', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
        'pole'=> array( 'label' => 'Pôle', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
        'delete'=> array( 'label' => 'Deleted', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
    ),
    'BINOMES' => array(
        'ID___COMET'=> array( 'label' => 'Id Comet', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 1, 'relate' => false),
        'NAME' => array( 'label' => 'Name', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
        'MISE___EN___PLACE' => array( 'label' => 'Mise en place', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
        'FIN' => array( 'label' => 'Fin', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
        'precision_lieu_c' => array( 'label' => 'Precision lieu', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
        'heure_babituelle_rencontre_c' => array( 'label' => 'heure_babituelle_rencontre_c', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
        'lieu_habituel_rencontre_c' => array( 'label' => 'lieu_habituel_rencontre_c', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
        'statut_c' => array( 'label' => 'statut_c', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
        'jour_habituel_rencontre_c' => array( 'label' => 'jour_habituel_rencontre_c', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
        'NOM___EQUIPE' => array( 'label' => 'NOM EQUIPE', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
        'pole' => array( 'label' => 'pole', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
        'annee_scolaire_c' => array( 'label' => 'annee_scolaire_c', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
        'TYPE___BOT___COMET' => array( 'label' => 'TYPE BOT COMET', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
        'delete'=> array( 'label' => 'Delete', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'BENEFICIAIRE'=> array( 'label' => 'Bénéficiaire', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'required_relationship' => 0, 'relate' => true), 
        'BENEVOLES'=> array( 'label' => 'Bénévoles', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'required_relationship' => 0, 'relate' => true), 
        'Reponse'=> array( 'label' => 'Reponse', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'required_relationship' => 0, 'relate' => true), 
        'REFERENT'=> array( 'label' => 'REFERENT', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'required_relationship' => 0, 'relate' => true), 
        'POLES'=> array( 'label' => 'POLES', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'required_relationship' => 0, 'relate' => true), 
    ),
    'POLE' => array(
        'prenom'=> array( 'label' => 'Prénom', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
        'nom'=> array( 'label' => 'Nom', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
        'mail'=> array( 'label' => 'Mail', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
        'numéro'=> array( 'label' => 'Numéro', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
        'nom___du___pole'=> array( 'label' => 'Nom du pôle', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
        'COMET ID' => array( 'label' => 'Comet ID', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'REFERENTS'=> array( 'label' => 'REFERENTS', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'required_relationship' => 0, 'relate' => true), 
        'BINOMES'=> array( 'label' => 'BINOMES', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'required_relationship' => 0, 'relate' => true), 
        'CONTACTS'=> array( 'label' => 'CONTACTS', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'required_relationship' => 0, 'relate' => true), 
    ),
    'REFERENTS' => array(
        'NOM'=> array( 'label' => 'Nom', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
        'PRENOM'=> array( 'label' => 'Nom', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
        'ID___COMET'=> array( 'label' => 'ID Comet', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
        'EMAIL'=> array( 'label' => 'Email', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
        'MOBILE'=> array( 'label' => 'Mobile', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
        'delete'=> array( 'label' => 'Delete', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'BINOMES'=> array( 'label' => 'BINOMES', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'required_relationship' => 0, 'relate' => true),
        'POLES'=> array( 'label' => 'POLES', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'required_relationship' => 0, 'relate' => true),
    ),
);

// Aiko supp
$moduleFields['appX0PhUGIkBTcWBE'] = array (
	'Aiko Auto Supr' => array(
        'LABEL'=> array( 'label' => 'Label', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
        'IDCOMET'=> array( 'label' => 'Id COMET', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
        'SyncSource'=> array( 'label' => 'Sync Source', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
        'DEVREC_ID'=> array( 'label' => 'Dev Rec_ID', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0)
    ),
);

// Mobilisation
$moduleFields['app5ustIjI5taRXJS'] = array (
	'COUPONS' => array(
		'fldsTwjBHZDgcO69j'=> array( 'label' => 'ID', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldcX0CaVrvhGXrUe'=> array( 'label' => 'Nom :', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldsP7jMxsgqPPyOO'=> array( 'label' => 'Date de création', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldy7Z0t0Ed0SldEV'=> array( 'label' => 'Date de modification', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldjRsDyoMd1qcAD5'=> array( 'label' => 'Modifié par', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldR1Na4VbmAW6wbb'=> array( 'label' => 'Modifié par 2', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldkbznnL4FRhX8kC'=> array( 'label' => 'Créé par', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fld30hDGrRtLjKmsK'=> array( 'label' => 'Créé par 2', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldIIWRG9nstIpHwN'=> array( 'label' => 'Description :', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldV4zC7Znz0LjIeN'=> array( 'label' => 'Supprimé', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldTPwd6ZsZnClhDp'=> array( 'label' => 'Utilisateur attribué :', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldfOdJ2mFAUleBrf'=> array( 'label' => 'Attribué à', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldiLSVg8oFpvlL2w'=> array( 'label' => 'Civilité', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldvLuidDhfqzlH6u'=> array( 'label' => 'Prénom :', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldnrNZBLmHKTNPa7'=> array( 'label' => 'Nom de famille :', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fld9pCF88v4M3I5Dh'=> array( 'label' => 'Nom : 2', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldgKhp6WRsHK9Z3U'=> array( 'label' => 'Titre :', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldPfqDgInzCuDTdy'=> array( 'label' => 'Photo', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldItYBkS0yzNEXmy'=> array( 'label' => 'Service :', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldXKt30kd9yddRfb'=> array( 'label' => 'Ne pas appeler :', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fld1C1CwPhNXAIkyw'=> array( 'label' => 'Téléphone (domicile) :', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldVNaQtq0ooJQKTA'=> array( 'label' => 'Tous les E-mails :', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldwEvgdvleCy4Vaw'=> array( 'label' => 'Téléphone mobile :', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldpyccALoVAHUO6h'=> array( 'label' => 'Téléphone du bureau :', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldcsIYjLaVBVBRKm'=> array( 'label' => 'Téléphone ', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldfes7GRbktyqvcw'=> array( 'label' => 'Fax :', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldaG35rEvmO9rm3m'=> array( 'label' => 'Adresse E-mail :', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldrQIDDoth61m4OR'=> array( 'label' => 'Autre E-mail :', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldsRVQY45ig5HgNJ'=> array( 'label' => 'E-mail invalide :', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldUCbOwzeMNJKXMo'=> array( 'label' => 'E-mail Opt Out :', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldiG5KYqRQxcD7HO'=> array( 'label' => 'Base légale', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fld2hrmwJ3czGbByT'=> array( 'label' => 'Date de révision de la base légale', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldCLVHrd0BRx7ZaJ'=> array( 'label' => 'Source de la base légale', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldowRReh6DMAhr57'=> array( 'label' => 'Adresse principale - Rue 1', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldBflkn3UrDpoA9k'=> array( 'label' => 'Adresse principale - Rue 2', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldolJL2VVSVeUPqd'=> array( 'label' => 'Adresse principale - Rue 3', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldGlrSLkqRbfZNI8'=> array( 'label' => 'Adresse principale - Ville', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldHmM4ZishIghtg5'=> array( 'label' => 'Adresse principale - Région', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldgwtcCK8bLoE5I8'=> array( 'label' => 'Adresse principale - Code Postal', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldGHLPj87YDQvjuO'=> array( 'label' => 'Adresse principale - Pays', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldVcoCoB0k4DfTGd'=> array( 'label' => 'Adresse secondaire - Rue 1', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldfpwchzAuOBf2JI'=> array( 'label' => 'Adresse secondaire - Rue 2', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldDu9xU0y69Knt5q'=> array( 'label' => 'Adresse secondaire - Rue 3', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldGjNS0md4z3d6rm'=> array( 'label' => 'Adresse secondaire - Ville', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldvuAdb7LZ3Jmx8o'=> array( 'label' => 'Adresse secondaire - Région', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldtaJd0O00VfiKIL'=> array( 'label' => 'Adresse secondaire - Code Postal', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fld6aZc1ijZgkEgbX'=> array( 'label' => 'Adresse secondaire - Pays', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldNFJy7XIEqlRrPd'=> array( 'label' => 'Assistant', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldkHt1FkgM6sl0b9'=> array( 'label' => 'Téléphone assistant', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldcXYPFs1L71xuo9'=> array( 'label' => 'E-mail(s) secondaire(s)', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldUIayNFGgVYIgPK'=> array( 'label' => 'Transformé', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fld18yIGT0I6ZAJZx'=> array( 'label' => 'Fait référence à :', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldMUbhXRuQRJKP24'=> array( 'label' => 'Origine du coupon:', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldXwVNFYqKywD76D'=> array( 'label' => 'Description de la principale origine du Coupon:', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldEI7AEhSDfynvFz'=> array( 'label' => 'Statut:', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldlhljropBT5b7lD'=> array( 'label' => 'Description Statut :', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fld0yIOeDwEguXItg'=> array( 'label' => 'Rend compte à (ID)', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldLqXSYPuMaZf6Ne'=> array( 'label' => 'Rend compte à:', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldeeoFoeiGvud04M'=> array( 'label' => 'Nom du compte :', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldpZnnwqP6rPlNcI'=> array( 'label' => 'Description compte', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldufIMv95ejYb94J'=> array( 'label' => 'Contact (ID)', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fld3enAgdHl34bEwg'=> array( 'label' => 'Partenaire (ID)', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldq5u2r91WRPB15s'=> array( 'label' => 'Affaire (ID)', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldLLEYAx4Xluvhhw'=> array( 'label' => 'Nom Affaire :', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldi09rKzhlCkspSl'=> array( 'label' => 'Montant Affaire :', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldxpzpfv7lx7IRpW'=> array( 'label' => 'Id Campagne communication', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldg78SmHS9IocNRx'=> array( 'label' => 'Campagne communication:', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldvgCPcJ3QazOWuF'=> array( 'label' => 'Statut d acceptation', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldKFx76rDYKjvnws'=> array( 'label' => 'Statut d acceptation 2', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldn6R6dmJUYyvLXs'=> array( 'label' => 'Statut d acceptation 3', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldmDfXCVGwcONZLJ'=> array( 'label' => 'Statut d acceptation 4', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldhYzFLmwWvn50KL'=> array( 'label' => 'Adresse E-mail : 2', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldylPfYOq5DaUNy6'=> array( 'label' => 'Autre E-mail : 2', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldiVpKSwGGOLhZEH'=> array( 'label' => 'E-mail Opt Out : 2', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldqTUZ8hWoIWioOg'=> array( 'label' => 'E-mail invalide : 2', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldPS5UAYRw7NGPlp'=> array( 'label' => 'Date de naissance :', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldygT8WOtF4sZclp'=> array( 'label' => 'Nom sur le portail :', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldcnYhSGq4ZXMClx'=> array( 'label' => 'Portail application:', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldxsoqHeoo2W7KmK'=> array( 'label' => 'Site web', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fld7JnqUcchADEylW'=> array( 'label' => 'LBL_CONT_INVITE_STATUS', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fld7f7NkoJeal1cCJ'=> array( 'label' => 'LBL_LIST_INVITE_STATUS_EVENT', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldBGkYEQz1XYYp8y'=> array( 'label' => 'LBL_LIST_INVITE_STATUS', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldmBy3DAA0uhtohf'=> array( 'label' => 'LBL_CONT_ACCEPT_STATUS', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldRl5QxPHKYIt2Ha'=> array( 'label' => 'LBL_LIST_ACCEPT_STATUS_EVENT', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldk7AWEyta8WTRoI'=> array( 'label' => 'Statut d acceptation 5', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldlgXfGWbHEMp2sZ'=> array( 'label' => 'Secteur d activité', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'flddu34KEELrJ1iEO'=> array( 'label' => 'Sera boursier', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'flddw1b6q9cNzXy8z'=> array( 'label' => 'Si plus étudiant, quelle filière ?', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldu2MWB1BTvNyyOZ'=> array( 'label' => 'Classe', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fld6yxjMtWPehvKWU'=> array( 'label' => 'L implication de la famille dans la scolarité', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldObLP2DWbNL6jMH'=> array( 'label' => 'Est boursier', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldvfygITfERD0cWf'=> array( 'label' => 'Diplôme préparé', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldCcZN9NfLnjtzn3'=> array( 'label' => 'Dimanche', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldxFohLsR7pHuVDa'=> array( 'label' => 'Autres suivis du mentoré (psychomotricité, orthophoniste, etc)', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldu9imp70Mm0D3QP'=> array( 'label' => 'Niveau scolaire', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldLONKgsifjNjS5b'=> array( 'label' => 'Le travail personnel', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldmyoRiG4uVpkmmp'=> array( 'label' => 'A-t-il déjà fait une colocation ?', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fld0ih5hdt82gSrma'=> array( 'label' => 'Vendredi', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldf2L5BN9jU6O4TF'=> array( 'label' => 'Année scolaire', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldXMLR8terNjqEYH'=> array( 'label' => 'Pourquoi souhaites-tu faire un service civique à l Afev ?', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldlUfS0Bnrf8UTH3'=> array( 'label' => 'URL pour le statut de la réunion', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldWtBx87EOc3baYV'=> array( 'label' => 'Nationalité', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldsdcDvQPmuNTOX9'=> array( 'label' => 'LBL_', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'flddCn492nfmfWQmh'=> array( 'label' => 'Situation', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldD2SJIwhcf1lgvH'=> array( 'label' => 'Pole id', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fld3V9PJfu0Alo8FC'=> array( 'label' => 'Nom', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldXo4mVRL2qqizG4'=> array( 'label' => 'Statut pendant le volontariat', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldBOCyDcsZUmvtHF'=> array( 'label' => 'Email du mentoré', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldUKVw4t5HJvUM9X'=> array( 'label' => 'Si plus étudiant, quel niveau ?', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldq3F9CrVOU4poJO'=> array( 'label' => 'Prénom', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldI5nTOy8oy5kqBM'=> array( 'label' => 'Samedi', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldpUk4jiDlQPB5JD'=> array( 'label' => 'LBL_REPERANT_CONTACT_ID', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldI7soVsJNHFAwkm'=> array( 'label' => 'L estime que le jeune a de lui-même', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldageDqyHrSJ570J'=> array( 'label' => 'Dernier diplôme obtenu', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldDIFLi5tqEBCnFW'=> array( 'label' => 'Centres d intérêts', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fld94lWtkxnc4GfcI'=> array( 'label' => 'Jeudi', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fld4ep2GpdYat9vqf'=> array( 'label' => 'Si oui, details', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fld2KhnZ2R4gIR5Ma'=> array( 'label' => 'Carte de transport', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldDLKjI73CVyewn2'=> array( 'label' => 'Langues parlées', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fld2mcw7LiR9u1HGY'=> array( 'label' => 'Mentorat reconduit', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fld9AYNwzQLEU7MIU'=> array( 'label' => 'Lundi', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldWOp6IF7mdt1Gaz'=> array( 'label' => 'Est étudiant', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldT4759ONX7cDwb9'=> array( 'label' => 'Période intégration colocation', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldb4JEPVTn41OcBL'=> array( 'label' => 'Relation', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldctOt3qDlHiT7Ht'=> array( 'label' => 'Niveau études', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldk93TffXgvoN16O'=> array( 'label' => 'Langues parlées 2', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldK0ft07vvWDK945'=> array( 'label' => 'Accord témoignage média', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'flduksYUAcH5PCiua'=> array( 'label' => 'Raisons de votre motivation', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldo9hVngp736idNF'=> array( 'label' => 'Envoi notification', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldMTfp3FBehg4u7b'=> array( 'label' => 'Etat de l enregistrement', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldLBKOxCTY3Teg2M'=> array( 'label' => 'Changement de ville prévu dans l année scolaire ?', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldcPXJ4tVsD5hNTA'=> array( 'label' => 'LBL_ANNEE_DEJA_ACCOMPAGNE', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldrtCDOYfe9jVvY7'=> array( 'label' => 'L ouverture culturelle / la mobilité', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fld9Gm0dtwnuWsm0k'=> array( 'label' => 'Quelle structure ?', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fld98AfSdVPLgDr98'=> array( 'label' => 'Partenaire repérant', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldoQPd9rAsbsKWM1'=> array( 'label' => 'Signature charte', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldJ8bOEOSwQDWx9S'=> array( 'label' => 'Commentaires', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fld6MMwwwol8yd3dA'=> array( 'label' => 'ENA', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldGagP4QHAt8htbe'=> array( 'label' => 'LBL_ETABLISSEMENT_ACCOUNT_ID', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fld3v6oryJRCY1whd'=> array( 'label' => 'Mercredi', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldiGguxs4cCFwVY4'=> array( 'label' => 'Préférence accompagnement', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fld9wLwY33WQghFoM'=> array( 'label' => 'Numéro de carte étudiant / INE', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'flddQ8qwjyelRwSMP'=> array( 'label' => 'Avec formation', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldo7HEUhoB5hNYAx'=> array( 'label' => 'Filière', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldTHQSMSuvlvGETC'=> array( 'label' => 'Mentorat à distance', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldf6PbDlxWBUXlUh'=> array( 'label' => 'Contact repérant', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldXN6zQuKhxvaDGS'=> array( 'label' => 'Établissement d enseignement', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldDrb5cwsNm09des'=> array( 'label' => 'Ses motivations', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fld3ZG74ADT9VqtS1'=> array( 'label' => 'Étudiant en mobilité internationale', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldTWruFzxjqsVFdU'=> array( 'label' => 'Type de coupon', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldygqkhdLB6UphOF'=> array( 'label' => 'Email repérant (obsolete)', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldDEBdLtqhVwrmsn'=> array( 'label' => 'Nationalité 2', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldYLwzvQmyo5bPlW'=> array( 'label' => 'Mardi', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldi5wStbxGmQj2od'=> array( 'label' => 'Véhicule personnel', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldsHjgZyRCMxGTXa'=> array( 'label' => 'Le rapport à l école', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fld22v7PcwvPzhIDF'=> array( 'label' => 'Type d actions menées', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fld1zXKRs1JheDOpA'=> array( 'label' => 'A-t-il déjà participé à une action associative et solidaire ?', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldbv9VAiwnBKqVeK'=> array( 'label' => 'L année prochaine tu serais', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldAhABJWhS2gYYQJ'=> array( 'label' => 'LBL_COMPOSANTE_ACCOUNT_ID', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldzSK5NqJ6T90gZv'=> array( 'label' => 'LBL_ADRESSE_FORMATION', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldrCJLwlSs0lR2E4'=> array( 'label' => 'LBL_ADS_CAMPAIGN', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldaooZGj8RQqcakA'=> array( 'label' => 'LBL_ADS_CONTENT', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldaskCRdz9EnCNpK'=> array( 'label' => 'LBL_ADS_ID_LEAD', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldxn7XZAqFXsPitt'=> array( 'label' => 'LBL_ADS_KEYWORDS', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldDT0GDeGOLuuyXO'=> array( 'label' => 'LBL_ADS_MEDIUM', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldxW3E3bEWgGx5wq'=> array( 'label' => 'Comment as-tu connu l’Afev ?', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldTtNkWo5eC8wIri'=> array( 'label' => 'Partenaire ou composante', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldQcTG9Ln2QvNSDr'=> array( 'label' => 'Date et heure de formation', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldXhXs1USXXcd666'=> array( 'label' => 'Formation', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fld3ovIQng7qCLsrE'=> array( 'label' => 'LBL_FORMATION_FP_EVENTS_ID', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldPHSUzJUNFSeQ3G'=> array( 'label' => 'Adresse', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fld3FMD0v0oMIQctR'=> array( 'label' => 'Status Géocode', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldXgZsHeDpPJ8Ij2'=> array( 'label' => 'Latitude', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldHWvon8MPFTjM3J'=> array( 'label' => 'Longitude', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldOywjbcoZDMoP3c'=> array( 'label' => 'Nom du pôle', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldKW98DPegV64RuS'=> array( 'label' => 'Travail en complément des études', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldWopOf0kox09k7M'=> array( 'label' => 'CONTACTS', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => true),
		'fld8afGboEfTb7XJ7'=> array( 'label' => 'POLES', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => true),
		'fldUw99qz1SXWm8Br'=> array( 'label' => 'PARTICIPATION RI', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => true),
		'fld3JpyUnkdooGXXx'=> array( 'label' => 'COMPOSANTES', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => true),
		'fld7QWV9eh59GEkoO'=> array( 'label' => 'DEV TEST ?', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fld1efUYoa7cWOad5'=> array( 'label' => 'FICHE BEN NUM REMPLIE', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldzKWmM6qxAE7knU'=> array( 'label' => 'utm_source', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldtGwBMvEzNEYSkk'=> array( 'label' => 'utm_medium', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fld5kV2umbzVwwHkY'=> array( 'label' => 'utm_campaign', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fld2jpSXvNov0SmvW'=> array( 'label' => 'utm_content', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fld2tHcATRYAqbuO0'=> array( 'label' => 'utm_term', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'flduGYPQNiE1VnkAW'=> array( 'label' => 'apiengagement_id', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
    ),
	'Relation POLE' => array(
        
		'fldNUZ1TkfO7uEjSF'=> array( 'label' => 'Label', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldaLPQ8EbyOpk61X'=> array( 'label' => 'record_type', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldNHqlGf5PJhYCMN'=> array( 'label' => 'pole_id', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => true),
		'fldWsjwPo27DVlYMy'=> array( 'label' => 'record_id', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => true),
		
	),
	'COMPOSANTES' => array(
		'fld0FmpZqG5wJFrCP'=> array( 'label' => 'ID', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldvR657BdJiJwD81Long'=> array( 'label' => 'Nom partenaire:', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldEphOcJmtdH0gkDLong'=> array( 'label' => 'Date de création :', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldJpm3YkzfQssEC2Long'=> array( 'label' => 'Date de modification :', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldaLna3H5GHtZ5GVLong'=> array( 'label' => 'Modifié par', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldkt6vU8JmxeWHD2'=> array( 'label' => 'Modifié par 2', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldw7e2GsLMlL44fU'=> array( 'label' => 'Créé par', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldFi5cIe4kIle2hL'=> array( 'label' => 'Créé par 2', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldPrxa8WrcFDjq7U'=> array( 'label' => 'Commentaires', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldIfJP3Bx2Otp0UH'=> array( 'label' => 'Supprimé', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldNvbl3LHJj9iNo9'=> array( 'label' => 'Utilisateur attribué :', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fld6WI5hyBWi5sw00'=> array( 'label' => 'Assigné à :', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldkYQoFe8lkkDZsE'=> array( 'label' => 'Type :', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldcLzrepa3PhbGEN'=> array( 'label' => 'Secteur activité :', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldTYuvLRTrVPVR1y'=> array( 'label' => 'Revenu annuel :', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fld19BU7qwfW2BtcO'=> array( 'label' => 'Fax :', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldqedHNqf6ZrrlFc'=> array( 'label' => 'Rue 1:', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldI4XiAAShVaRjOw'=> array( 'label' => 'Rue 2', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldw0LMDb4LLNZ0Kr'=> array( 'label' => 'Rue 3', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldsgbR75p4OusdZv'=> array( 'label' => 'Rue 4', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldNisoL2UOdXJCk4'=> array( 'label' => 'Ville:', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldvFDLf6OztRWJ28'=> array( 'label' => 'Région:', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldcF8l3DACiWfjuD'=> array( 'label' => 'Code Postal:', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fld4BI0kRNjMpoYWH'=> array( 'label' => 'Pays:', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fld7uuYKM9fgllBcM'=> array( 'label' => 'Classement :', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldXt1Xsmxy2IYx3O'=> array( 'label' => 'Téléphone du standard:', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldFV7xOj9WIG71xK'=> array( 'label' => 'Autre téléphone :', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldukvjWEIj7YEtGy'=> array( 'label' => 'Site Web :', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldDzyHbPbXUZ7Jjs'=> array( 'label' => 'Propriétaire :', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldnnZQTknRyR63q1'=> array( 'label' => 'Employés :', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldZnlTuH44KB3oxC'=> array( 'label' => 'Symbole Tycker :', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldRPfBvmb2I8KFO9'=> array( 'label' => 'Livraison - Rue :', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldDsSQuJBLCUHr3U'=> array( 'label' => 'Livraison - Rue 2', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldNyy9uj6jtwXHVt'=> array( 'label' => 'Livraison - Rue 3', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldW4apVPMWliRCAg'=> array( 'label' => 'Livraison - Rue 4', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fld687YV4I4VtKtiy'=> array( 'label' => 'Livraison - Ville :', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldPxprte3yXHkUb8'=> array( 'label' => 'Livraison - Région :', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldWUmcQ60JaWpNZU'=> array( 'label' => 'Livraison - Code Postal :', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldiWwBqIBUDFzL6M'=> array( 'label' => 'Livraison - Pays :', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldMp0poKnORaoA5m'=> array( 'label' => 'Email général:', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldJjh0AoKauJegiO'=> array( 'label' => 'E-mail(s) secondaire(s)', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldnhUFSLDKMhfNsd'=> array( 'label' => 'Rattaché à (ID)', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldVuOYCChUbq5p1l'=> array( 'label' => 'Code APE :', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldwU94MlU4YnauRa'=> array( 'label' => 'Rattaché à:', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fld1ik3eNnEIu7EuE'=> array( 'label' => 'E-mail Opt Out :', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldMQZ3zd6HGq3UmX'=> array( 'label' => 'E-mail invalide :', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'flduvrJgPl8ug50Yf'=> array( 'label' => 'N importe quel E-mails :', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fld3Lj7UiN7yehWGP'=> array( 'label' => 'Campagne communication ID', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldvvoweIyObbo7ef'=> array( 'label' => 'Campagne communication:', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldhCTS0vEU7VF6Bi'=> array( 'label' => 'REP/REP+', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldswzGB6r1q6G00T'=> array( 'label' => 'Objectifs', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldBYv4XGcE54DVLS'=> array( 'label' => 'Accepte les sollicitations pour la communication', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldjMQqnikAw0khB3'=> array( 'label' => 'Type de partenaire', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fld27TiCk6uyuy2XD'=> array( 'label' => 'e valorisation mentorat', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldbGFHeKCzx2dIwi'=> array( 'label' => 'Lien valorisation mentorat', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldWoKgy6gWjQppFf'=> array( 'label' => 'Etablissement enseignement supérieur', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldmPEt799vARgHIl'=> array( 'label' => 'Adresse', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fld3gipwr9PUGELDH'=> array( 'label' => 'Status Géocode', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldFud2pzJdC0z0dy'=> array( 'label' => 'Latitude', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldbFPWY1oSk3TXfP'=> array( 'label' => 'Longitude', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fld7GDVJAHshM0tui'=> array( 'label' => 'COUPONS', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => true),
		'fldBQBCfr1ZgVJmE3'=> array( 'label' => 'ETABLISSEMENTS', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => true),
		'fldDQbqwlY5irE8wQ'=> array( 'label' => 'POLES', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => true),
		'fldzN9XTath3C0IpV'=> array( 'label' => 'DEV TEST ?', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),

	),
	'ETABLISSEMENTS' => array(
		'fldju02qVMRi2iGXZ'=> array( 'label' => 'ID', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldjv6J8HQQKwyQJP'=> array( 'label' => 'Nom', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldQcFvWET1YmMrSS'=> array( 'label' => 'Date de création', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldrEidouF44QyGtU'=> array( 'label' => 'Date de modification', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fld12ProKjc47X1Lz'=> array( 'label' => 'Modifié par', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldt6SsAzKv3BZDBt'=> array( 'label' => 'Modifié par 2', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldckzZ0TVfFXOvjk'=> array( 'label' => 'Créé par', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldVP0B8dqimZ1zIU'=> array( 'label' => 'Créé par 2', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fld6Jz0x6Z0yJhQhP'=> array( 'label' => 'Description', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldQfwhAJfrhyTGCy'=> array( 'label' => 'Supprimé', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldmlUB6AMKL0ZPKN'=> array( 'label' => 'Assigné à (ID)', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fld0JiuQkvKxXM4Uw'=> array( 'label' => 'Assigné à', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldtQXUZaFFuobq08'=> array( 'label' => 'Ville', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldg7LvJNIpnpbnQi'=> array( 'label' => 'Mail établissement', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldphGWthLXM43G2q'=> array( 'label' => 'Partenaire', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => true),
		'fldT5NzrrmMjJMqXp'=> array( 'label' => 'COMPOSANTES', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => true),
		'fldQeGpNIkMdlzMd0'=> array( 'label' => 'POLES (from COMPOSANTES)', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => true),
		'fldRc8rN4P1KQfT1p'=> array( 'label' => 'DEV TEST ?', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),

	),
	'EVENEMENTS' => array(
		'fld6Z4Y4W0Id8QpAH'=> array( 'label' => 'À distance', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldD7CyqYbr4WNx6c'=> array( 'label' => 'Accepter la redirection URL', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldrlnu90pOskvCYq'=> array( 'label' => 'Adresse ou lien Google Meet', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldnwmIqCLbzBpZze'=> array( 'label' => 'Année scolaire', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldxF65Lb0ytT8eWS'=> array( 'label' => 'Assigné à', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldcRf9CNfoc7OqC4'=> array( 'label' => 'Budget', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldLmkZLrv0VbtCB1'=> array( 'label' => 'Créé par', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fld9y3JApPYw3YAkb'=> array( 'label' => 'Créé par 2', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldmhGqc9h2UPCu2a'=> array( 'label' => 'Date de création', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fld3tttWqV9gJ2Cpv'=> array( 'label' => 'Date de début', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldP1NzDw0tIRYvyj'=> array( 'label' => 'Date de fin', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldZbM9sGwno9Y1qf'=> array( 'label' => 'Date de modification', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldaz6nsmngPiFncr'=> array( 'label' => 'Devise :', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldW1X26JtD5VrWar'=> array( 'label' => 'Durée', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldAwYEMmwAHC5P2M'=> array( 'label' => 'Durée (heures)', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fld9lPyI57AylfyjD'=> array( 'label' => 'Durée (minutes)', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldJYjWjQWqqSOsOt'=> array( 'label' => 'Etat de l enregistrement', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldYiVOuMCipGl2av'=> array( 'label' => 'Formateur', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldbhLw9VZNK2qLWc'=> array( 'label' => 'Formation complète', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldGp0V04JyHrJp2w'=> array( 'label' => 'ID', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'flda7a17WUtyFZtAz'=> array( 'label' => 'ID de l utilisateur attribué', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldqPwJNn0q67aHw3'=> array( 'label' => 'Informations complémentaires', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldFVaBc0qwGjB36B'=> array( 'label' => 'LBL_FORMATEUR_CONTACT_ID', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldgAWWE0ltf9ONZR'=> array( 'label' => 'LBL_RESPONSE_LINK', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldZm0cyvFGX6l0Qp'=> array( 'label' => 'LBL_RESPONSE_LINK_DECLINED', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fld50CLi1HKqLmsmI'=> array( 'label' => 'Lieux', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldT0bnnvpRPlXruk'=> array( 'label' => 'Modèle d E-mail d invitation', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fld1n3VaJJpGEPkPN'=> array( 'label' => 'Modifié par', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fld04UyY4jFEUjRtj'=> array( 'label' => 'Modifié par 2', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldJVwTB0spk5ZWd9'=> array( 'label' => 'Nb particpants max', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldC3Rfjy7TUZJVqa'=> array( 'label' => 'Refuser la redirection d URL', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldQ4p0A6k03sTVEo'=> array( 'label' => 'Retours engagés', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldzee5DjZrsBwnM0'=> array( 'label' => 'Retours formateurs', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldQI3bpIAjbCK4hA'=> array( 'label' => 'Retours salariés', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldFriStvFZUHlOW9'=> array( 'label' => 'Statut', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldgETPz9yoBKTMK1'=> array( 'label' => 'Supprimé', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldu3qsqZFmR0BEeK'=> array( 'label' => 'Titre', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldrfkJdARDc2VQaL'=> array( 'label' => 'Type d évènement', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldFaeT8vfhw79ViZ'=> array( 'label' => 'Type de formation/réunion', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldu6JbiJDi3Qcfif'=> array( 'label' => 'PARTICIPATION RI', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => true),
		'fldyb4QDma9N0eV8S'=> array( 'label' => 'POLES', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => true),
		'flda0lVrbz61xGRTI'=> array( 'label' => 'DEV TEST ?', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),

	),
	'POLES' => array(
		'fldC6GvLH0zO5g1bb'=> array( 'label' => 'Nom', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'flddQu5AwhpVDe9lM'=> array( 'label' => 'Date de création', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldYT0FG4xnN5TDbu'=> array( 'label' => 'Date de modification', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldXSOQ8YQ8pg2xtZ'=> array( 'label' => 'Description', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldFo6wnyUWWvDI9d'=> array( 'label' => 'Supprimé', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldgkM0TdBFGvLdjR'=> array( 'label' => 'Non héritable', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fld0MnQT0wriSuDjP'=> array( 'label' => 'Identifiant Facebook', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldIiynh5KYgAxYni'=> array( 'label' => 'Identifiant Instagram', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldwNzsoNQEtwp3mi'=> array( 'label' => 'Inactif', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fld9eV9pBJsRwQKNC'=> array( 'label' => 'MAD', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldNUk7McovO0WcOI'=> array( 'label' => 'Région', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldCU4okx1W4KAM3g'=> array( 'label' => 'ID Comet', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fld6wQK0PA12sZFx0'=> array( 'label' => 'SLACK CHAN ID', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldYcQftpuDXhpqQm'=> array( 'label' => 'CONTACTS', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => true),
		'fldZGJkZfGccIgZVz'=> array( 'label' => 'COUPONS', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => true),
		'fld548tF3RfNVsv0d'=> array( 'label' => 'COMPOSANTES', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => true),
		'fldaKI8mY9mKKqKvz'=> array( 'label' => 'EVENEMENTS', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => true),
		'fldbJVJamSxhGwbk0'=> array( 'label' => 'UTILISATEURS', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => true),
		'fldi8UI4Xqf343dJI'=> array( 'label' => 'Prénom référent.e', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldHFZF2BvrsFwwi9'=> array( 'label' => 'Nom référent.e', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldNTtHMVWGj2Z7nh'=> array( 'label' => 'Téléphone référent.e', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fld4ynwOWcqouwYHr'=> array( 'label' => 'Mail référent.e', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldvCwllO0498Sdl8'=> array( 'label' => 'Villes', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),

	),
	'UTILISATEURS' => array(
		'fld4C44q13DlaLrrm'=> array( 'label' => 'Nom d utilisateur', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldkCgDPMeWhVV0nY'=> array( 'label' => 'Mot de passe', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldlSbEkHdsTrg2mB'=> array( 'label' => 'Mot de passe généré par le système', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldCUpyuCM2xFjKRd'=> array( 'label' => 'Dernier changement du Mot de passe', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldNZixyULYkDhNbw'=> array( 'label' => 'ID d authentification', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fld4JMXST2K3nZZU2'=> array( 'label' => 'Is SuiteCRM User', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldGPz1YxLiCWhc8n'=> array( 'label' => 'Prénom', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldq1VunNwxZZuTN4'=> array( 'label' => 'Nom de famille', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldVML7bfTiamvxez'=> array( 'label' => 'Administrateur ?', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldMKQKLJ0sOljWIb'=> array( 'label' => 'Authentification externe', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldh0sSiawnsQ1Vam'=> array( 'label' => 'Description', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fld4AxeVYrfcKW8Y2'=> array( 'label' => 'Date de création', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldlbnUYAfBkhCZOb'=> array( 'label' => 'Date de modification', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldURmzYvJTufEzvR'=> array( 'label' => 'Fonction', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldbQahCaepJDvwLR'=> array( 'label' => 'Photo', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldCVwCcEWQZHBvID'=> array( 'label' => 'Service', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldaaJX5Fn4dScS1R'=> array( 'label' => 'Ligne directe', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldyZaAP1OpxtZ10f'=> array( 'label' => 'Téléphone Mobile', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fld9DFu7DbIvdowwN'=> array( 'label' => 'Téléphone Bureau', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldFDgXmiHCo1jidL'=> array( 'label' => 'Téléphone Autre', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldCTVtTp3ZVRLE6E'=> array( 'label' => 'Fax', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fld4dpim3bGdzJDuT'=> array( 'label' => 'Statut', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldvZwPpuBOcsmU2V'=> array( 'label' => 'Adresse Rue', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fld8J4AMK29kGd7dJ'=> array( 'label' => 'Adresse Ville', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldhtw5Q1EzOEmtK8'=> array( 'label' => 'Adresse Région', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'flddnoqnkF4PykXt3'=> array( 'label' => 'Adresse Pays', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldOHJnfsSvemBQ1A'=> array( 'label' => 'Adresse Code Postal', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldn7NsvLmRnCO3u0'=> array( 'label' => 'Supprimé', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fld14iF1LLsDP2r9B'=> array( 'label' => 'Utilisateur API Portail', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldqVSiyfBcA90WZB'=> array( 'label' => 'Afficher en tant qu employé', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldDZfTvRZ8zzBeHB'=> array( 'label' => 'Statut en tant qu employé', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fld6cZSYaG6G3ZEhh'=> array( 'label' => 'Nom IM', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldGcpw5r4Pwjcqvn'=> array( 'label' => 'Type IM', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldvTBkp7JXfGor9b'=> array( 'label' => 'Utilisateur groupe', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldsbRulka0ZDTMcv'=> array( 'label' => 'Authentification en deux étapes', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldjtozX1BVLVOZpn'=> array( 'label' => 'Interface de l authentification à deux facteurs', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldGOrxfSWVJKjTrn'=> array( 'label' => 'Régions', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldUv6K5B3qW7fP4V'=> array( 'label' => 'Email', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldkndSVBg8atsjVL'=> array( 'label' => 'Date de naissance', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldzQJxi7zxWVo6hR'=> array( 'label' => 'Structure associée', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldiinKARhAlWJbk2'=> array( 'label' => 'droits', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldvOtRv2YvfAqQOQ'=> array( 'label' => 'MAD pôle sauvegarde', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'flddSLDY6u7p9cFsx'=> array( 'label' => 'Pôles', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldMgHTuhsPeKecaF'=> array( 'label' => 'Jeton de sécurité QlikCloud', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldBZZpQPo3zATqMg'=> array( 'label' => 'Rôle disponibles', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldEZwKofQlvSJkMm'=> array( 'label' => 'POLES', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => true),

	),
	'PARTICIPATION RI' => array(
		'fldiXX1KBp4Gl55zw'=> array( 'label' => 'ID', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldYvyAHOntuqhWbC'=> array( 'label' => 'Date de modification', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldjyKAQSd1hDmgU9'=> array( 'label' => 'Supprimé', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldL4qph2Lg65xKjz'=> array( 'label' => 'IDA', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldtIpKCdlbykhkm5'=> array( 'label' => 'IDB', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldupTDWb5Hw734VK'=> array( 'label' => 'Statut invitation', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldZA7RFzeon8In5T'=> array( 'label' => 'Statut acceptation', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldiqweSyapKu5vjI'=> array( 'label' => 'Réponse email', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldgP06QBzNR04Wux'=> array( 'label' => 'Date de modification 2', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldx66gWeVZqNjLtd'=> array( 'label' => 'COUPONS', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => true),
		'fldzKn6i2TQREz7yb'=> array( 'label' => 'EVENEMENTS', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => true),
		'fld9NewQqcWSMg7rR'=> array( 'label' => 'DEV TEST ?', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldIyRoF4es2GHnwB'=> array( 'label' => 'apiengagement_id', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fld7XyJC3deIsUi9W'=> array( 'label' => 'utm_source', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fld2jrzyKoWxgRy07'=> array( 'label' => 'utm_medium', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldhjrWZMvk0V8Dox'=> array( 'label' => 'utm_campaign', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldd62c003RfQjfcY'=> array( 'label' => 'utm_content', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),
		'fldBUu85vhDwA3u1d'=> array( 'label' => 'utm_term', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'relate' => false),

	),
);