regle_jobscheduler:
    resource: "@RegleBundle/Resources/config/routing/jobscheduler.yml"
    prefix:   /jobscheduler

regle_inputs:
    path:  /inputs/
    defaults: { _controller: RegleBundle:Default:ruleInputs }
    requirements:
        methods:  POST    
 
regle_inputs_name_unique:
    path:  /inputs/name_unique/
    defaults: { _controller: RegleBundle:Default:ruleNameUniq }
    requirements:
        methods:  POST

regle_panel:
    path:  /panel/
    defaults: { _controller: RegleBundle:Default:panel }

regle_update:
    path:  /update/{id}
    defaults: { _controller: RegleBundle:Default:ruleUpdActive }

regle_logs:
    path: /getlogs/{id}
    defaults: { _controller: RegleBundle:Default:displayLogs }

path_fiche_params_update:
    path:  /update/params/{id}
    defaults: { _controller: RegleBundle:Default:ruleUpdParams }

path_fiche_params_simulate:
    path:  /simule/{id}
    defaults: { _controller: RegleBundle:Default:ruleSimulateTransfers }

path_info_field:
    path:  /info/{type}/{field}/
    defaults: { _controller: RegleBundle:Default:infoField }
    requirements:
        methods:  GET  

path_info_field_not_param:
    path:  /info/
    defaults: { _controller: RegleBundle:Default:infoField }

graph_type_error_doc:
    path:  /graph/type/error/doc
    defaults: { _controller: RegleBundle:Default:graphTypeError }    

graph_type_transfer_rule:
    path:  /graph/type/transfer/rule
    defaults: { _controller: RegleBundle:Default:graphTransferRule }    

graph_type_transfer_histo:
    path:  /graph/type/transfer/histo
    defaults: { _controller: RegleBundle:Default:graphTransferHisto }    

graph_type_job_histo:
    path:  /graph/type/job/histo
    defaults: { _controller: RegleBundle:Default:graphJobHisto }  

regle_template:
    path:  /list/template/
    defaults: { _controller: RegleBundle:Default:listTemplate }

regle_submodules:
    path:  /submodules/
    defaults: { _controller: RegleBundle:Default:listSubModules }
    requirements:
        methods:  POST    

regle_validation_animation:
    path:  /validation/
    defaults: { _controller: RegleBundle:Default:validationAnimation }

regle_stepone_animation:
    path:  /create/
    defaults: { _controller: RegleBundle:Default:ruleStepOneAnimation }  

regle_list_module:
    path:  /list/module/
    defaults: { _controller: RegleBundle:Default:ruleListModule }

regle_steptwo:
    path:  /create/step2/
    defaults: { _controller: RegleBundle:Default:ruleStepTwo }
    requirements:
        methods:  POST
        
regle_stepthree:
    path:  /create/step3/{id}
    defaults: { _controller: RegleBundle:Default:ruleStepThree, id: 0 }

regle_validation:
    path:  /create/step3/validation/
    defaults: { _controller: RegleBundle:Default:ruleValidation }
    requirements:
        methods:  POST

regle_simulation:
    path:  /create/step3/simulation/
    defaults: { _controller: RegleBundle:Default:ruleSimulation }
    requirements:
        methods:  POST
        
regle_formula:
    path:  /create/step3/formula/
    defaults: { _controller: RegleBundle:Default:ruleVerifFormula }
    requirements:
        methods:  POST        
        
regle_connector_create:
    path:  /connector/create/
    defaults: { _controller: RegleBundle:Connector:create }
    
regle_connector_create_out:
    path:  /connector/createout/{type}
    defaults: { _controller: RegleBundle:Connector:createOut }   
       
regle_connector_insert_solution:
    path:  /connector/insert/solution/
    defaults: { _controller: RegleBundle:Connector:connectorInsertSolution }
    
regle_connector_insert:
    path:  /connector/insert/
    defaults: { _controller: RegleBundle:Connector:connectorInsert }
    
connector_callback:
    path:  /connector/callback/
    defaults: { _controller: RegleBundle:Connector:callBack }    
        
regle_connector_by_solution:
    path:  /connector/list/solution/
    defaults: { _controller: RegleBundle:Connector:connectorListSolution }
    
regle_connector_list:
    path:  /connector/list/
    defaults: { _controller: RegleBundle:Connector:connectorList, page: 1 }

regle_connector_page:
    path:  /connector/list/page-{page}
    defaults: { _controller: RegleBundle:Connector:connectorList }
    requirements:
        page: \d+

connector_delete:
    path:  /connector/delete/{id}
    defaults: { _controller: RegleBundle:Connector:connectorDelete }
    
upload:
    path:  /connector/upload/{solution}
    defaults: { _controller: RegleBundle:Connector:upload }    

connector_open:
    path:  /connector/view/{id}
    defaults: { _controller: RegleBundle:Connector:connectorOpen }

flux_error_rule:
    path:  /flux/error/{id}/
    defaults: { _controller: RegleBundle:Flux:fluxErrorByRule  }

flux_info:
    path:  /flux/{id}/log/
    defaults: { _controller: RegleBundle:Flux:fluxInfo, page: 1  }

flux_info_page:
    path: /flux/{id}/log/page-{page}
    defaults: { _controller: RegleBundle:Flux:fluxInfo }
    requirements:
        page: \d+

flux_list_delete_filter:
    path:  /flux/list/delete/filter/
    defaults: { _controller: RegleBundle:Flux:fluxListDeleteFilter }

flux_rerun:
    path:  /flux/rerun/{id}
    defaults: { _controller: RegleBundle:Flux:fluxRerun }
    
flux_cancel:
    path:  /flux/cancel/{id}
    defaults: { _controller: RegleBundle:Flux:fluxCancel }    

flux_readrecord:
    path:  /flux/readrecord/{id}
    defaults: { _controller: RegleBundle:Flux:fluxReadRecord }    

flux_save:
    path:  /flux/save/
    defaults: { _controller: RegleBundle:Flux:fluxSave }

flux_btn_dyn:
    path:  /flux/{id}/action/{method}/solution/{solution}
    defaults: { _controller: RegleBundle:Flux:fluxBtnDyn }

flux_list:
    path:  /flux/list/search-{search}
    defaults: { _controller: RegleBundle:Flux:fluxList, page: 1 }

flux_list_page:
    path:  /flux/list/page-{page}
    defaults: { _controller: RegleBundle:Flux:fluxList }
    requirements:
        page: \d+   

flux_mass_cancel:
    path:  /flux/masscancel/
    defaults: { _controller: RegleBundle:Flux:fluxMassCancel }

flux_mass_run:
    path:  /flux/massrun/
    defaults: { _controller: RegleBundle:Flux:fluxMassRun }

regle_list:
    path:  /list/
    defaults: { _controller: RegleBundle:Default:ruleList, page: 1 }

regle_list_page:
    path:  /list/page-{page}
    defaults: { _controller: RegleBundle:Default:ruleList }
    requirements:
        page: \d+    

regle_delete:
    path:  /delete/{id}
    defaults: { _controller: RegleBundle:Default:ruleDelete }
    
regle_displayflux:
    path:  /displayflux/{id}
    defaults: { _controller: RegleBundle:Default:displayFlux }

regle_edit:
    path:  /edit/{id}
    defaults: { _controller: RegleBundle:Default:ruleEdit }  

regle_open:
    path:  /view/{id}
    defaults: { _controller: RegleBundle:Default:ruleOpen }

regle_exec:
    path:  /exec/{id}
    defaults: { _controller: RegleBundle:Default:ruleExec }  

my_account:
    path:  /account/
    defaults: { _controller: RegleBundle:Account:myAccount }


account_locale:
    path:  /account/locale/
    defaults: { _controller: RegleBundle:Account:changeLocale }
    options:
        expose: true

task_list:
    path:  /task/list/
    defaults: { _controller: RegleBundle:Task:taskList, page: 1 }

task_list_page:
    path:  /task/list/page-{page}
    defaults: { _controller: RegleBundle:Task:taskList }
    requirements:
        page: \d+

task_view:
    path:  /task/view/{id}/log/
    defaults: { _controller: RegleBundle:Task:viewTask, page: 1 }

task_view_page:
    path:  /task/view/{id}/log/page-{page}
    defaults: { _controller: RegleBundle:Task:viewTask }
    requirements:
        page: \d+

task_stop:
    path:  /task/stop/{id}
    defaults: { _controller: RegleBundle:Task:stopTask, page: 1 }


management_smtp_index:
    path: /managementsmtp/
    defaults: {_controller: RegleBundle:ManagementSMTP:index}

management_smtp_create:
    path: /managementsmtp/readConfig
    defaults: {_controller: RegleBundle:ManagementSMTP:createConfig}
    methods:  [POST, GET]
