parameters:
    mailer_transport: sendmail
    mailer_host: localhost
    mailer_port: '26'
    mailer_auth_mode: null
    mailer_encryption: null
    mailer_user: admin
    mailer_password: 'Recette?1'
