services:
  _defaults:
    autowire: true      
    autoconfigure: true 
    public: false      


  App\Premium\Solutions\suitecrmpremium:
      decorates: App\Solutions\suitecrm
      decoration_on_invalid: ignore
      decoration_priority: 1
  # App\Custom\Solutions\suitecrmcustom:
  #     decorates: App\Solutions\suitecrm
  #     decoration_on_invalid: ignore
  #     decoration_priority: 1