parameters:
#    hello.example.class: Tuto\HelloBundle\Example

services:
    kernel.listener.response_listener:
        class: Myddleware\LoginBundle\EventListener\ResponseListener
        tags:
           - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
