<?php

$moduleFields = [
    'pages' => [
        'id' => ['label' => 'ID', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'date' => ['label' => 'Date', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'date_gmt' => ['label' => 'Date GMT', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'guid' => ['label' => 'Guid', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'modified' => ['label' => 'Modified', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'modified_gmt' => ['label' => 'Modified GMT', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'slug' => ['label' => 'Slug', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'status' => ['label' => 'Status', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'type' => ['label' => 'Type', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'link' => ['label' => 'Link', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'date' => ['label' => 'Date', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'title' => ['label' => 'Title', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'content' => ['label' => 'Content', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'excerpt' => ['label' => 'Excerpt', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'author' => ['label' => 'Author', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'featured_media' => ['label' => 'Featured media', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'parent' => ['label' => 'Parent', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'menu_order' => ['label' => 'Menu order', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'comment_status' => ['label' => 'Comment status', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'ping_status' => ['label' => 'Ping status', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'template' => ['label' => 'Template', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        '_links' => ['label' => '_links', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
    ],
    'posts' => [
        'id' => ['label' => 'ID', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'date' => ['label' => 'Date', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'date_gmt' => ['label' => 'Date GMT', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'guid' => ['label' => 'Guid', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'modified' => ['label' => 'Modified', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'modified_gmt' => ['label' => 'Modified GMT', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'slug' => ['label' => 'Slug', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'status' => ['label' => 'Status', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'type' => ['label' => 'Type', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'link' => ['label' => 'Link', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'date' => ['label' => 'Date', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'title' => ['label' => 'Title', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'content' => ['label' => 'Content', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'excerpt' => ['label' => 'Excerpt', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'author' => ['label' => 'Author', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'featured_media' => ['label' => 'Featured media', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'comment_status' => ['label' => 'Comment status', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'ping_status' => ['label' => 'Ping status', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'template' => ['label' => 'Template', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'format' => ['label' => 'Format', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'meta' => ['label' => 'Meta', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'categories' => ['label' => 'Categories', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'tags' => ['label' => 'Tags', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        '_links' => ['label' => '_links', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
    ],
    // 'categories' => array(
    //     'id' => array( 'label' => 'ID', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0),
    //     'count' => array( 'label' => 'Count', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0),
    //     'description' => array( 'label' => 'Description', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0),
    //     'link' => array( 'label' => 'Link', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0),
    //     'name' => array( 'label' => 'Name', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0),
    //     'slug' => array( 'label' => 'Slug', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0),
    //     'taxonomy' => array( 'label' => 'Taxonomy', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0),
    //     'parent' => array( 'label' => 'Parent', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0),
    //     'meta' => array( 'label' => 'Meta', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0),
    //     '_links' => array( 'label' => '__links', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0),
    // ),
 //TODO
    // 'types'=>	array(

    // ),
    // 'statuses'=> array(

    // ),
    // 'settings' =>	array(

    // ),
    // 'search' =>	array(

    // ),
    // 'block-types'=>	array(

    // ),
    // 'blocks' =>	array(

    // ),
    // 'block-renderer' =>	array(

    // ),
    // 'plugins' => array(

    // ),
    // 'media' => array(

    // ),
    // 'taxonomies' => array(

    // ),
    // 'tags' => array(

    // ),
    // 'themes' => array(

    // ),
    'comments' => [
        'id' => ['label' => 'ID', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'post' => ['label' => 'Post', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'parent' => ['label' => 'Parent', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'author' => ['label' => 'Author', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'author_name' => ['label' => 'Author Name', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'author_url' => ['label' => 'Author URL', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'date' => ['label' => 'Date', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'date_gmt' => ['label' => 'Date GMT', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'content' => ['label' => 'Content', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'link' => ['label' => 'Link', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'status' => ['label' => 'Status', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'type' => ['label' => 'Type', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'author_avatar_urls' => ['label' => 'Author Avatar URLs', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'meta' => ['label' => 'Meta', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        '_links' => ['label' => '__links', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
    ],

//these modules are part of the Woocommerce Event manager plugin and are used in the wooeventmanager connector
    'mep_events' => [
        'id' => ['label' => 'ID', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'date' => ['label' => 'Date', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'date_gmt' => ['label' => 'Date GMT', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'guid__rendered' => ['label' => 'Guid', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'modified' => ['label' => 'Modified', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'modified_gmt' => ['label' => 'Modified GMT', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'slug' => ['label' => 'Slug', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'status' => ['label' => 'Status', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'type' => ['label' => 'Type', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'link' => ['label' => 'Link', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'title__rendered' => ['label' => 'Title rendered', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'content__rendered' => ['label' => 'Content rendered', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'content__protected' => ['label' => 'Content protected', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'excerpt__rendered' => ['label' => 'Excerpt rendered', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'excerpt__protected' => ['label' => 'Excerpt protected', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'featured_media' => ['label' => 'Featured Media', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'template' => ['label' => 'Template', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'mep_cat' => ['label' => 'MEP Categories', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'mep_org' => ['label' => 'MEP Organizers', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        // 'event_informations' => array( 'label' => 'Event informations', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0),
        'event_informations___edit_lock' => ['label' => 'Event info : edit lock', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'event_informations__check_if_run_once' => ['label' => 'Event info : check if run once', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'event_informations___edit_last' => ['label' => 'Event info : edit last', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'event_informations__mep_available_seat' => ['label' => 'Event info : mep available seat', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'event_informations__mep_reg_status' => ['label' => 'Event info : mep reg status', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'event_informations___tax_status' => ['label' => 'Event info : tax status', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'event_informations___tax_class' => ['label' => 'Event info : tax class', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'event_informations__mep_event_ticket_type' => ['label' => 'Event info : mep event ticket type', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'event_informations__mep_rt_event_status' => ['label' => 'Event info : mep rt event status', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'event_informations__mep_rt_event_attandence_mode' => ['label' => 'Event info : mep rt event attendance mode', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'event_informations__mep_rt_event_prvdate' => ['label' => 'Event info : mep rt event prvdate', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'event_informations__mep_full_name' => ['label' => 'Event info : mep full name', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'event_informations__mep_reg_email' => ['label' => 'Event info : mep reg email', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'event_informations__mep_reg_phone' => ['label' => 'Event info : mep reg phone', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'event_informations__mep_reg_address' => ['label' => 'Event info : mep reg address', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'event_informations__mep_reg_designation' => ['label' => 'Event info : mep reg designation', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'event_informations__mep_reg_website' => ['label' => 'Event info : mep reg website', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'event_informations__mep_reg_veg' => ['label' => 'Event info : mep reg veg', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'event_informations__mep_reg_company' => ['label' => 'Event info : mep reg company', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'event_informations__mep_reg_gender' => ['label' => 'Event info : mep reg gender', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'event_informations__mep_reg_tshirtsize' => ['label' => 'Event info : mep reg tshirt size', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'event_informations__mep_reg_tshirtsize_list' => ['label' => 'Event info : mep reg tshirt size list', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'event_informations__mep_event_template' => ['label' => 'Event info : mep event template', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'event_informations__mep_org_address' => ['label' => 'Event info : mep org address', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'event_informations__event_start_date' => ['label' => 'Event info : start date', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'event_informations__event_start_time' => ['label' => 'Event info : start time', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'event_informations__event_end_date' => ['label' => 'Event info : end date', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'event_informations__event_end_time' => ['label' => 'Event info : end time', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'event_informations__event_start_datetime' => ['label' => 'Event info : event start datetime', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'event_informations__event_end_datetime' => ['label' => 'Event info : event end datetime', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'event_informations__event_expire_datetime' => ['label' => 'Event info : event expire date time', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'event_informations___manage_stock' => ['label' => 'Event info : manage stock', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'event_informations___stock' => ['label' => 'Event info : stock', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'event_informations___stock_msg' => ['label' => 'Event info : stock msg', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'event_informations__longitude' => ['label' => 'Event info : longitude', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'event_informations__latitude' => ['label' => 'Event info : latitude', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'event_informations__location_name' => ['label' => 'Event info : location name', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'event_informations__mep_location_venue' => ['label' => 'Event info : location venue', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'event_informations__mep_street' => ['label' => 'Event info : mep street', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'event_informations___sold_individually' => ['label' => 'Event info : sold individually', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'event_informations__mep_city' => ['label' => 'Event info : mep city', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'event_informations__mep_state' => ['label' => 'Event info : mep state', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'event_informations__mep_postcode' => ['label' => 'Event info : mep postcode', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'event_informations__mep_country' => ['label' => 'Event info : mep country', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'event_informations___price' => ['label' => 'Event info : price', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'event_informations___virtual' => ['label' => 'Event info : virtual', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'event_informations___sku' => ['label' => 'Event info : sku', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        // 'event_informations__mep_event_more_date' => array( 'label' => 'Event info : mep event more date', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0),
        'event_informations__mep_list_thumbnail' => ['label' => 'Event info : mep list thumbnail', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'event_informations__mep_event_cc_email_text' => ['label' => 'Event info : mep event cc email text', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'event_informations__event_feature_image' => ['label' => 'Event info : event feature image', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        '_links' => ['label' => '__links', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
    ],
    'mep_event_more_date' => [
        'id' => ['label' => 'ID', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'event_more_start_date' => ['label' => 'Start date', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'event_more_start_time' => ['label' => 'Start time', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'event_more_end_date' => ['label' => 'End date', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'event_more_end_time' => ['label' => 'End time', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
    ],

    'mep_org' => [
        'id' => ['label' => 'ID', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'count' => ['label' => 'Count', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'description' => ['label' => 'Description', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'link' => ['label' => 'Link', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'name' => ['label' => 'Name', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'slug' => ['label' => 'Slug', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'taxonomy' => ['label' => 'Taxonomy', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'parent' => ['label' => 'Parent', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'meta' => ['label' => 'Meta', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        '_links' => ['label' => 'ID', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
    ],
    'mep_cat' => [
        'id' => ['label' => 'ID', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'count' => ['label' => 'Count', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'description' => ['label' => 'Description', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'link' => ['label' => 'Link', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'name' => ['label' => 'Name', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'slug' => ['label' => 'Slug', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'taxonomy' => ['label' => 'Taxonomy', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'parent' => ['label' => 'Parent', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'meta' => ['label' => 'Meta', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        '_links' => ['label' => 'ID', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
    ],
    'mep_event_attendee' => [
        'id' => ['label' => 'ID', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'date' => ['label' => 'Date', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'date_gmt' => ['label' => 'Date GMT', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'guid__rendered' => ['label' => 'Guid rendered', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'modified' => ['label' => 'Modified', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'modified_gmt' => ['label' => 'Modified GMT', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'slug' => ['label' => 'Slug', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'status' => ['label' => 'Status', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'type' => ['label' => 'Type', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'link' => ['label' => 'Link', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'title__rendered' => ['label' => 'Title__rendered', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'template' => ['label' => 'Template', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'attendee_informations__mep_event_show_attendee_list' => ['label' => 'Attendee infos : Mep_event_show_attendee_list', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'attendee_informations__mep_event_attendee_edit_frontend' => ['label' => 'Attendee infos : Mep_event_attendee_edit_frontend', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'attendee_informations__ea_name' => ['label' => 'Attendee infos : EA name', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'attendee_informations__ea_address_1' => ['label' => 'Attendee infos : EA address_1', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'attendee_informations__ea_email' => ['label' => 'Attendee infos : EA email', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'attendee_informations__ea_phone' => ['label' => 'Attendee infos : EA phone', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'attendee_informations__ea_gender' => ['label' => 'Attendee infos : EA gender', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'attendee_informations__ea_company' => ['label' => 'Attendee infos : EA company', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'attendee_informations__ea_desg' => ['label' => 'Attendee infos : EA desg', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'attendee_informations__ea_website' => ['label' => 'Attendee infos : EA website', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'attendee_informations__ea_vegetarian' => ['label' => 'Attendee infos : EA vegetarian', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'attendee_informations__ea_tshirtsize' => ['label' => 'Attendee infos : EA tshirtsize', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'attendee_informations__ea_ticket_type' => ['label' => 'Attendee infos : EA ticket type', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'attendee_informations__ea_ticket_qty' => ['label' => 'Attendee infos : EA ticket qty', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'attendee_informations__ea_ticket_price' => ['label' => 'Attendee infos : EA ticket price', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'attendee_informations__ea_payment_method' => ['label' => 'Attendee infos : EA payment method', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'attendee_informations__ea_event_name' => ['label' => 'Attendee infos : EA event name', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'attendee_informations__ea_event_id' => ['label' => 'Attendee infos : EA event ID', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'attendee_informations__ea_order_id' => ['label' => 'Attendee infos : EA order ID', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'attendee_informations__ea_user_id' => ['label' => 'Attendee infos : EA user ID', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'attendee_informations__mep_checkin' => ['label' => 'Attendee infos : Mep checkin', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'attendee_informations__ea_ticket_no' => ['label' => 'Attendee infos : EA ticket no', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'attendee_informations__ea_event_date' => ['label' => 'Attendee infos : EA event date', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'attendee_informations__ea_order_status' => ['label' => 'Attendee infos : EAorder status', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'attendee_informations__ea_partecipazione_cognome' => ['label' => 'Attendee infos : EA partecipazione cognome', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
    ],
];

$fieldsRelate = [
    'mep_events' => [
        'mep_cat__0' => ['label' => 'MEP Category', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'mep_org__0' => ['label' => 'MEP Organizer', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'event_informations__link_wc_product' => ['label' => 'Event info : product ID', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
    ],
    'mep_event_more_date' => [
        'event_id' => ['label' => 'MEP Event ID', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
    ],
];
