<?php
/*********************************************************************************
 * This file is part of Myddleware.

 * @package Myddleware
 * @copyright Copyright (C) 2013 - 2015  Stéphane Faure - CRMconsult EURL
 * @copyright Copyright (C) 2015 - 2016  Stéphane Faure - Myddleware ltd - contact@myddleware.com
 * @link http://www.myddleware.com

 This file is part of Myddleware.

 Myddleware is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 Myddleware is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with Myddleware.  If not, see <http://www.gnu.org/licenses/>.
*********************************************************************************/

$moduleFields = [
    'customers' => [
        'id' => ['label' => 'ID customer', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'gender' => ['label' => 'Gender', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'option' => ['m' => 'Homme', 'f' => 'Femme']],
        'first_name' => ['label' => 'First name', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 1],
        'last_name' => ['label' => 'Last_name', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 1],
        'email' => ['label' => 'Email', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 1],
        'birth_date' => ['label' => 'Birth date', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'phone' => ['label' => 'Phone', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'fax' => ['label' => 'Fax', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'discount' => ['label' => 'Discount', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'credit' => ['label' => 'Credit', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'credit_expiration_date' => ['label' => 'Credit expiration date', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'reward_points' => ['label' => 'Reward points', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'password' => ['label' => 'Password', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'date_created' => ['label' => 'Date created', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'date_modified' => ['label' => 'Date modified', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'auto_connect_url' => ['label' => 'Auto connect url', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'photo' => ['label' => 'Photo', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
    ],
    'orders' => [
        'id' => ['label' => 'ID order', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'language' => ['label' => 'Language', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'option' => ['m' => 'Homme', 'f' => 'Femme']],
        'status' => ['label' => 'Status', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 1],
        'notes' => ['label' => 'Notes', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'date_created' => ['label' => 'Date created', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'date_modified' => ['label' => 'Date modified', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'date_finished' => ['label' => 'Date finished', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'referer' => ['label' => 'Referer', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'currency' => ['label' => 'Currency', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'shipping__tracking_code' => ['label' => 'Shipping tracking code', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'shipping__tracking_url' => ['label' => 'Shipping tracking url', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'shipping__method_code' => ['label' => 'Shipping method code', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'shipping__method_name' => ['label' => 'Shipping method name', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'payment__method_name' => ['label' => 'Payment method name', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'payment__method_code' => ['label' => 'Payment method code', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'customer_info__name' => ['label' => 'Customer name', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'customer_info__company' => ['label' => 'Customer company', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'customer_info__city' => ['label' => 'Customer city', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'customer_info__street_address' => ['label' => 'Customer street_address', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'customer_info__suburb' => ['label' => 'Customer suburb', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'customer_info__doorcode' => ['label' => 'Customer doorcode', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'customer_info__floor' => ['label' => 'Customer floor', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'customer_info__postcode' => ['label' => 'Customer postcode', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'customer_info__state' => ['label' => 'Customer state', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'customer_info__country' => ['label' => 'Customer country', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'customer_info__phone' => ['label' => 'Customer phone', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'customer_info__email' => ['label' => 'Customer email', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'customer_info__ip' => ['label' => 'Customer IP', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'delivery_address__gender' => ['label' => 'Delivery address gender', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'option' => ['m' => 'Homme', 'f' => 'Femme']],
        'delivery_address__name' => ['label' => 'Delivery address name', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'delivery_address__company' => ['label' => 'Delivery address company', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'delivery_address__phone' => ['label' => 'Delivery address phone', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'delivery_address__street_address' => ['label' => 'Delivery address street_address', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'delivery_address__suburb' => ['label' => 'Delivery address suburb', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'delivery_address__doorcode' => ['label' => 'Delivery address doorcode', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'delivery_address__floor' => ['label' => 'Delivery address floor', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'delivery_address__city' => ['label' => 'Delivery address city', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'delivery_address__postcode' => ['label' => 'Delivery address postcode', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'delivery_address__state' => ['label' => 'Delivery address state', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'delivery_address__country' => ['label' => 'Delivery address country', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'delivery_address__country_code' => ['label' => 'Delivery address country code', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'billing_address__gender' => ['label' => 'Billing address gender', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'option' => ['m' => 'Homme', 'f' => 'Femme']],
        'billing_address__name' => ['label' => 'Billing address name', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'billing_address__company' => ['label' => 'Billing address company', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'billing_address__phone' => ['label' => 'Billing address phone', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'billing_address__street_address' => ['label' => 'Billing address street_address', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'billing_address__suburb' => ['label' => 'Billing address suburb', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'billing_address__doorcode' => ['label' => 'Billing address doorcode', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'billing_address__floor' => ['label' => 'Billing address floor', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'billing_address__city' => ['label' => 'Billing address city', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'billing_address__postcode' => ['label' => 'Billing address postcode', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'billing_address__state' => ['label' => 'Billing address state', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'billing_address__country' => ['label' => 'Billing address country', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'billing_address__country_code' => ['label' => 'Billing address country code', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'origin__mobile' => ['label' => 'Origin mobile', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'origin__cash_register' => ['label' => 'Origin cash register', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'origin__back_office' => ['label' => 'Origin back office', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'origin__api' => ['label' => 'Origin api', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
    ],
    'orders_delivery_address' => [
        'gender' => ['label' => 'Delivery address gender', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'option' => ['m' => 'Homme', 'f' => 'Femme']],
        'name' => ['label' => 'Delivery address name', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'company' => ['label' => 'Delivery address company', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'phone' => ['label' => 'Delivery address phone', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'street_address' => ['label' => 'Delivery address street_address', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'suburb' => ['label' => 'Delivery address suburb', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'doorcode' => ['label' => 'Delivery address doorcode', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'floor' => ['label' => 'Delivery address floor', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'city' => ['label' => 'Delivery address city', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'postcode' => ['label' => 'Delivery address postcode', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'state' => ['label' => 'Delivery address state', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'country' => ['label' => 'Delivery address country', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'country_code' => ['label' => 'Delivery address country code', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
    ],
    'orders_billing_address' => [
        'gender' => ['label' => 'Delivery address gender', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'option' => ['m' => 'Homme', 'f' => 'Femme']],
        'name' => ['label' => 'Delivery address name', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'company' => ['label' => 'Delivery address company', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'phone' => ['label' => 'Delivery address phone', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'street_address' => ['label' => 'Delivery address street_address', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'suburb' => ['label' => 'Delivery address suburb', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'doorcode' => ['label' => 'Delivery address doorcode', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'floor' => ['label' => 'Delivery address floor', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'city' => ['label' => 'Delivery address city', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'postcode' => ['label' => 'Delivery address postcode', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'state' => ['label' => 'Delivery address state', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'country' => ['label' => 'Delivery address country', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'country_code' => ['label' => 'Delivery address country code', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
    ],
    'orders_products' => [
        'id' => ['label' => 'ID order product', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'reference' => ['label' => 'Reference', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'stock_reference' => ['label' => 'Stock reference', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'name' => ['label' => 'Name', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'quantity' => ['label' => 'Quantity', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'cost' => ['label' => 'Cost', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'final_price' => ['label' => 'Final price', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'tax_rate' => ['label' => 'Tax rate', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'date_added' => ['label' => 'Date added', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'weight' => ['label' => 'Weight', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'brand_name' => ['label' => 'Brand name', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
    ],
    'customers_addresses' => [
        'address_id' => ['label' => 'ID address', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'address_company' => ['label' => 'Company', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'address_vat_number' => ['label' => 'Vat_number', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'address_gender' => ['label' => 'Gender', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'option' => ['m' => 'Homme', 'f' => 'Femme']],
        'address_first_name' => ['label' => 'First name', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'address_last_name' => ['label' => 'Last_name', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 1],
        'address_phone' => ['label' => 'Phone', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'address_street' => ['label' => 'Street', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'address_suburb' => ['label' => 'Suburb', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'address_doorcode' => ['label' => 'Door code', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'address_floor' => ['label' => 'Floor', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'address_postcode' => ['label' => 'Postcode', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'address_city' => ['label' => 'City', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'address_state' => ['label' => 'State', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'address_department' => ['label' => 'Department', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'address_region' => ['label' => 'Region', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'address_latitude' => ['label' => 'Latitude', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'address_longitude' => ['label' => 'Longitude', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'country_id' => ['label' => 'Country ID', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
    ],
    'products' => [
        'id' => ['label' => 'ID product', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'reference' => ['label' => 'Reference', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'ean' => ['label' => 'stock_ean', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'isbn' => ['label' => 'Isbn', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'status' => ['label' => 'Status', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'option' => ['0' => 'Désactivé', '1' => 'Activé']],
        'guarantee' => ['label' => 'Guarantee', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'default_cost' => ['label' => 'Default cost', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'price' => ['label' => 'Price', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'price_recommended' => ['label' => 'Price recommended', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'date_added' => ['label' => 'Date added', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'date_modified' => ['label' => 'Date modified', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'date_available' => ['label' => 'Date available', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'shipping_delay' => ['label' => 'Shipping delay', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'tax_rate' => ['label' => 'Tax rate', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'cart_min_quantity' => ['label' => 'Cart min quantity', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'cart_max_quantity' => ['label' => 'Cart max quantity', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'image' => ['label' => 'Image', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'image_2' => ['label' => 'Image 2', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'image_3' => ['label' => 'Image 3', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'image_4' => ['label' => 'Image 4', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'image_5' => ['label' => 'Image 5', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'image_6' => ['label' => 'Image 6', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'image_7' => ['label' => 'Image 7', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'image_8' => ['label' => 'Image 8', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'image_9' => ['label' => 'Image 9', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'image_10' => ['label' => 'Image 10', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'stock_total_quantity' => ['label' => 'Stock total quantity', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'weight' => ['label' => 'Weight', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'volume' => ['label' => 'Volume', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'height' => ['label' => 'Height', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'width' => ['label' => 'Width', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'length' => ['label' => 'Length', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'reward_points' => ['label' => 'Reward points', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'disable_stock' => ['label' => 'Disable stock', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'template' => ['label' => 'Template', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'sort_order' => ['label' => 'Sort order', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'multilangual__ISO__name' => ['label' => 'Name', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'multilangual__ISO__short_description' => ['label' => 'Short description', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'multilangual__ISO__description' => ['label' => 'Description', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'multilangual__ISO__description_title' => ['label' => 'Description title', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'multilangual__ISO__description2' => ['label' => 'Description 2', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'multilangual__ISO__description_title2' => ['label' => 'Description title 2', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'multilangual__ISO__description3' => ['label' => 'Description 3', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'multilangual__ISO__description_title3' => ['label' => 'Description title 3', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'multilangual__ISO__description4' => ['label' => 'Description 4', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'multilangual__ISO__description_title4' => ['label' => 'Description title 4', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'multilangual__ISO__head_title_tag' => ['label' => 'Head title tag', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'multilangual__ISO__meta_description_tag' => ['label' => 'Meta description tag', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'multilangual__ISO__meta_keywords_tag' => ['label' => 'Meta keywords tag', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'multilangual__ISO__h1_tag' => ['label' => 'H1 tag', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'multilangual__ISO__h2_tag' => ['label' => 'H2 tag', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'multilangual__ISO__h3_tag' => ['label' => 'H3 tag', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'multilangual__ISO__url_title' => ['label' => 'URL title', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'multilangual__ISO__views' => ['label' => 'Views', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
    ],
    'products_options' => [
        'attribute_sort_order' => ['label' => 'Attribute sort order', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'attribute_price' => ['label' => 'Attribute price', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'attribute_price_prefix' => ['label' => 'Attribute price prefix', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'attribute_photo' => ['label' => 'Attribute photo', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'attribute_weight' => ['label' => 'Attribute weight', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'attribute_volume' => ['label' => 'Attribute volume', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
    ],
    'options' => [
        'id' => ['label' => 'ID option', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'multilangual__ISO__name' => ['label' => 'Name', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'multilangual__ISO__comment' => ['label' => 'Comment', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'type' => ['label' => 'Type', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'option' => ['0' => 'Liste déroulante', '1' => 'Champ Texte', '2' => 'Bouton Radio', '3' => 'Case à cocher', '4' => 'Zone de texte', '5' => 'Fichier à transférer', '6' => 'Icone']],
        'length' => ['label' => 'Length', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'required' => ['label' => 'Required', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'option' => ['0' => 'Non', '1' => 'Oui']],
        'track_stock' => ['label' => 'ID option', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'option' => ['0' => 'Non', '1' => 'Oui']],
    ],
    'options_values' => [
        'id' => ['label' => 'ID value', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'multilangual__ISO__value_name' => ['label' => 'Name', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'multilangual__ISO__value_image' => ['label' => 'Image', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
    ],
    'products_stock' => [
        'stock_reference' => ['label' => 'Reference', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'stock_ean' => ['label' => 'EAN', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
    ],
    'products_stock_options' => [
    ],
    'products_stock_entries' => [
        'stock_entry_date' => ['label' => 'Entry date', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'stock_entry_quantity' => ['label' => 'Entry quantity', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'stock_entry_cost' => ['label' => 'Entry cost', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
    ],
    'categories' => [
        'id' => ['label' => 'ID category', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'image' => ['label' => 'Image', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'status' => ['label' => 'Status', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'option' => ['0' => 'Désactivé', '1' => 'Activé']],
        'date_added' => ['label' => 'Date added', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'date_modified' => ['label' => 'Date modified', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'date_available' => ['label' => 'Date available', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'path' => ['label' => 'Path', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'sort_order' => ['label' => 'Sort order', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'multilangual__ISO__name' => ['label' => 'Name', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'multilangual__ISO__description' => ['label' => 'description', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'multilangual__ISO__custom_content' => ['label' => 'Custom content', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'multilangual__ISO__head_title_tag' => ['label' => 'Head title tag', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'multilangual__ISO__meta_description_tag' => ['label' => 'Meta description tag', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'multilangual__ISO__meta_keywords_tag' => ['label' => 'Meta keywords tag', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'multilangual__ISO__h1_tag' => ['label' => 'H1 tag', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'multilangual__ISO__h2_tag' => ['label' => 'H2 tag', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'multilangual__ISO__h3_tag' => ['label' => 'H3 tag', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
    ],
    'brands' => [
        'id' => ['label' => 'ID brand', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'image' => ['label' => 'Image', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'name' => ['label' => 'Name', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'date_added' => ['label' => 'Date added', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'date_modified' => ['label' => 'Date modified', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'multilangual__ISO__description' => ['label' => 'description', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'multilangual__ISO__meta_title_tag' => ['label' => 'Meta title tag', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'multilangual__ISO__meta_description_tag' => ['label' => 'Meta description tag', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
        'multilangual__ISO__meta_keywords_tag' => ['label' => 'Meta keywords tag', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0],
    ],
];

$fieldsRelate = [
    'customers' => [
        'store_id' => ['label' => 'Store ID', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'required_relationship' => 0],
        'group_id' => ['label' => 'Group ID', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'required_relationship' => 0],
        'default_address_id' => ['label' => 'Default address id', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'required_relationship' => 0],
    ],
    'customers_addresses' => [
        'customers_id' => ['label' => 'Customer ID', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'required_relationship' => 0],
    ],
    'products' => [
        'pictogram_id' => ['label' => 'Pictogram ID', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'required_relationship' => 0],
        'brand_id' => ['label' => 'Brand ID', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'required_relationship' => 0],
        'category_id' => ['label' => 'Category ID', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'required_relationship' => 0],
        'supplier_id' => ['label' => 'Supplier ID', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'required_relationship' => 0],
        'option_id' => ['label' => 'Option ID', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'required_relationship' => 0],
        'criterion_id' => ['label' => 'Criterion ID', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'required_relationship' => 0],
        'stock_reference' => ['label' => 'Stock reference', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'required_relationship' => 0],
    ],
    'categories' => [
        'parent_id' => ['label' => 'Parent ID (0 if no parent)', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'required_relationship' => 0],
        'store_id' => ['label' => 'Store ID', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'required_relationship' => 0],
    ],
    'orders' => [
        'store_id' => ['label' => 'Store ID', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'required_relationship' => 0],
        'customer_info__id' => ['label' => 'Customer ID', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'required_relationship' => 0],
        'product_id' => ['label' => 'Product ID', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'required_relationship' => 0],
    ],
    'orders_products' => [
        'order_id' => ['label' => 'Order ID', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'required_relationship' => 0],
    ],
    'products_options' => [
        'product_id' => ['label' => 'Product ID', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'required_relationship' => 0],
        'option_id' => ['label' => 'Option ID', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'required_relationship' => 0],
        'option_value_id' => ['label' => 'Option value ID', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'required_relationship' => 0],
    ],
    'products_stock_options' => [
        'stock_reference' => ['label' => 'Stock reference', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'required_relationship' => 0],
        'option_id' => ['label' => 'Option ID', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'required_relationship' => 0],
        'option_value_id' => ['label' => 'Option value ID', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'required_relationship' => 0],
    ],
    'products_stock_entries' => [
        'stock_reference' => ['label' => 'Stock reference', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'required_relationship' => 0],
    ],
    'products_stock' => [
        'product_id' => ['label' => 'Product ID', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'required_relationship' => 0],
    ],
    'options_values' => [
        'option_id' => ['label' => 'Option ID', 'type' => 'varchar(255)', 'type_bdd' => 'varchar(255)', 'required' => 0, 'required_relationship' => 0],
    ],
];
